### ISSUE TITLE
Written file has the wrong size on Windows

### ISSUE THREAD

**Issue by Baenimyr** [syoyo/safetensors-cpp#3]
The `save_to_file` function create a buffer of the good size, but the file contains more bytes.
The buffer size was checked using a debugging tool.

# Context
Platform: Windows
just one small tensor: {"test": F32 [30, 300]}

# Fix
Opening the targeted file with `std::ios_base::binary` seems to fix the problem.
I suspect Windows to make a character conversion like "\n" => "\r\n".

**Comment by syoyo** [comment]
Please attach reproducible code/file.

I don't see any issue with serialize-example.cc on VS2022.
I have added `std::ios::binary` just in case: https://github.com/syoyo/safetensors-cpp/commit/b16b75203112a0439a2d084e0aab03c6058ef599
